export const types={
    
    ADD_TASK:'ADD_TASK',
    EDIT_VALUE:'EDIT_VALUE',

    DELETE_TASK:'DELETE_TASK',
    FETCH_TASK_LIST:'FETCH_TASK_LIST',

    EDIT_INPUT:'@INPUTS/EDIT',
    UPDATE_INPUT:'@INPUTS/UPDATE',

    //Report
    GET_WEEKLY:'@WEEKLY/LIST/GET',
    FETCH_WEEKLY:'@WEEKLY/LIST/FETCH',

    GET_MONTHLY:'@MONTHLY/LIST/GET',
    FETCH_MONTHLY:'@MONTHLY/LIST/FETCH',

    GET_HOURLY:'@HOURLY/LIST/GET',
    FETCH_HOURLY:'@HOURLY/LIST/FETCH',

    GET_LIST:'@/TASK/LIST/GET',
    FETCH_LIST:'@/TASK/LIST/FETCH'
}